#info.artifactId: @project.artifactId@
#info.version: @project.version@
spring:
  profiles:
    active: dev
server:
  port: 31136
  tomcat:
    uri-encoding: UTF-8
    keep-alive-timeout: 0
#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
---
spring:
  profiles: prod
  application:
    name: zjAI
  cloud:
    inetutils:
      preferred-networks: 172.16.10
    nacos:
      discovery:
        server-addr: 172.16.10.76:28848
  freemarker:
    cache: false
logging:
  level:
    org:
      springframework:
        web: info
  path: /data/logs/AIYun/kdd/
  config: classpath:logback-prod.xml
---
spring:
  profiles: dev
  application:
    name: zjAI
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  freemarker:
    cache: false
logging:
  level:
    org:
      springframework:
        web: info
  path: logs/kdd
  config: classpath:logback-prod.xml
---
spring:
  profiles: HKProd
  application:
    name: zjAI
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  freemarker:
    cache: false
logging:
  level:
    org:
      springframework:
        web: info
  path: /home/yey/logs/AIYun/scmj
  config: classpath:logback-prod.xml
---
spring:
  profiles: AliStage
  application:
    name: zjAI
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.190.103:8848
  freemarker:
    cache: false
---
spring:
  profiles: HKAli
  application:
    name: zjAI
  cloud:
    nacos:
      discovery:
        server-addr: 172.31.132.163:29038
  freemarker:
    cache: false
logging:
  level:
    org:
      springframework:
        web: info
  path: /more/logs/AIYun/zj
  config: classpath:logback-prod.xml